name = "smartfinance-backend"
main = "worker/src/index.js"
compatibility_date = "2024-09-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "smart-finance"
database_id = "e97d4fb7-a757-4ccd-af4c-8fe649f8090b"
migrations_dir = "migrations"